INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Acceso', '', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Accesos', 'Control de Accesos', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Tipo', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Tipos', 'Tipo de Usuarios', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Modulo', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Modulos', 'Control de Modulos', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Start', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('store', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cart', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('storeL', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cartL', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Productos', 'Control de Inventario', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Producto', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('User', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Users', 'Control de Usuarios', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Roles', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Checkout', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Historial', 'Mis Ordenes', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Ordenes', 'Manejo de Ordenes', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Orden', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlDsc`, `mdlState`, `mdlClass`) VALUES ('Config', 'Configuración de Usuario', 'ACT', 'MNU');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Approved', 'ACT', 'PGE');
INSERT INTO `pharmacare`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Canceled', 'ACT', 'PGE');

